#!/bin/bash

shopt -s globstar

find $VIMWIKI_PATH -type d | \
    awk -F "/" '{ for (i = 6; i < NF; i++) { printf("%s/", $i) } print $NF }' | \
    dmenu -l 30 | \
    awk '{printf("%s%s/",ENVIRON["VIMWIKI_PATH"], $0)}' | \
    find -name "*.md" -type f -files0-from - | \
    awk '{printf("\"%s\"\n", $0)}' | \
    sort | \
    xargs -r cat - | \
    pandoc -t pdf -f markdown+lists_without_preceding_blankline | \
    zathura -

